volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: alekseyemv/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: alekseyemv/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: alekseyemv/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
      - frontend
