# Generated by Django 3.2.16 on 2025-09-28 04:30

import functools

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Количество ингредиента в рецепте, которое сравнивается с минимальным значением', validators=[functools.partial(api.validators.validate_value_interval, *(), **{'max_value': 32000, 'min_value': 1})], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, help_text='Время приготовления рецепта в минутах', validators=[functools.partial(api.validators.validate_value_interval, *(), **{'max_value': 32000, 'min_value': 1})], verbose_name='Время приготовления (минуты)'),
        ),
    ]
