# Generated by Django 3.2.16 on 2025-09-23 07:29

import api.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20250923_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(help_text='Автор рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, help_text='Время приготовления рецепта в минутах', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение не может быть меньше 1')], verbose_name='Время приготовления (минуты)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Размер изображения рецепта (максимум MAX_FILE_SIZE МБ)', upload_to='recipes/images/', validators=[functools.partial(api.validators.validate_picture_format, *(), **{'max_file_size': 5242880})], verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ингредиенты для рецепта', related_name='recipes', through='recipes.IngredientRecipe', to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Название рецепта', max_length=256, validators=[django.core.validators.MinLengthValidator(2, 'Название должно быть не менее 2 символов.')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Автоматически заполняемая дата публикации рецепта', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tеги для категоризации рецепта', related_name='recipes', to='recipes.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(help_text='Подробное описание процесса приготовления', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Название тега', max_length=32, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Автоматически генерируемый идетификатор на основе названия', max_length=32, unique=True, verbose_name='Идентификатор'),
        ),
    ]
