# Generated by Django 3.2.16 on 2025-09-23 07:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20250923_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт, связанный с пользователем', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipe_set', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, создавший связь с рецептом', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Количество ингредиента в рецепте, которое сравнивается с минимальным значением', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение не может быть меньше 1')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='ingredient',
            field=models.ForeignKey(help_text='Ингредиент для рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_set', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт, к которому относится ингредиент', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientrecipe_set', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт, связанный с пользователем', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_recipe_set', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, создавший связь с рецептом', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
