# Generated by Django 3.2.16 on 2025-09-23 07:19

import functools

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Аватар пользователя', null=True, upload_to='users/images/', validators=[functools.partial(api.validators.validate_picture_format, *(), **{'max_file_size': 1048576})], verbose_name='Аватар'),
        ),
    ]
