# Generated by Django 3.2.16 on 2025-09-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким email уже существует'}, help_text='Уникальный email-адрес пользователя.', max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
