# Generated by Django 3.2.4 on 2025-08-30 06:00

from django.db import migrations
import django.db.models.manager
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250805_0920'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('accounts', users.managers.CreateUserManager()),
            ],
        ),
    ]
