# Generated by Django 3.2.4 on 2025-08-30 06:17

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.CreateUserManager()),
            ],
        ),
    ]
